kind: pipeline
type: docker
name: default

steps:
  - name: sonar-analyses
    image: hub.codefirst.iut.uca.fr/camille.petitalot/drone-sonarplugin-reactnative:latest
    commands:
      - cd Source/Trek12
      - npm install
      - sonar-scanner -X -Dsonar.projectKey=Trek12_toto -Dsonar.sources=. -Dsonar.host.url=$${PLUGIN_SONAR_HOST} 
        -Dsonar.login=squ_ffb2ad2b21b57a60523bea9a4a58891c97c09f14

    secrets: [ SECRET_SONAR_LOGIN ]
    settings:
      sonar_host: https://codefirst.iut.uca.fr/sonar/
      sonar_token:
        from_secret: SECRET_SONAR_LOGIN