kind: pipeline
type: docker
name: default

steps:
  - name: install-dependencies
    image: node:14-alpine
    commands:
      - apk add --no-cache bash
      - npm ci

  - name: build
    image: node:14-alpine
    commands:
      - npm run build

  - name: test
    image: node:14-alpine
    commands:
      - npm run test