kind: pipeline
type: docker
name: default

steps:
  - name: sonar-analyses
    image: hub.codefirst.iut.uca.fr/camille.petitalot/drone-sonarplugin-reactnative:latest
    commands:
      - cd Source/Trek12
      - npm install
      - npm run test
      - ls ./Tests
      - sonar-scanner -X -Dsonar.projectKey=Trek12 -Dsonar.sources=. -Dsonar.host.url=$${PLUGIN_SONAR_HOST} 
        -Dsonar.login=sqp_cfb8f45ecad5a399cb45e9fcb01cb41e3a222bdd -Dsonar.javascript.lcov.reportPaths=./Tests/coverage/lcov.info 
        -Dsonar.exclusions=**/lcov-report/**

    secrets: [ SECRET_SONAR_LOGIN ]
    settings:
      sonar_host: https://codefirst.iut.uca.fr/sonar/
      sonar_token:
        from_secret: SECRET_SONAR_LOGIN