kind: pipeline
type: docker
name: default

steps:
  - name: sonar-analyses
    image: hub.codefirst.iut.uca.fr/camille.petitalot/drone-sonarplugin-reactnative:latest
    commands:
      - cd Source/Trek12
      - npm install
      - sonar-scanner -X -Dsonar.projectKey=Trek12 -Dsonar.sources=. -Dsonar.host.url=$${PLUGIN_SONAR_HOST} 
        -Dsonar.login=sqp_bb5fa46dbc811c1bc40630985b9ece8123a6bf3f

    secrets: [ SECRET_SONAR_LOGIN ]
    settings:
      sonar_host: https://codefirst.iut.uca.fr/sonar/
      sonar_token:
        from_secret: SECRET_SONAR_LOGIN