export const ID_PLAYER = 'ID_PLAYER';

export const PSEUDO_PLAYER = 'PSEUDO_PLAYER';

export const CURRENT_GAME = 'CURRENT_GAME';

export const CURRENT_PLAYER = 'CURRENT_PLAYER';

export const CREATE_GAME  = 'CREATE_GAME';

export const CURRENT_GAMEFACTORY = 'CURRENT_GAMEFACTORY';

export const CREATE_GAMEFACTORY = 'CREATE_GAMEFACTORY';

